name: Publish Docker image

on:
  push:
    branches: [ main ]

    
  workflow_dispatch:

jobs:
  push_to_registry:
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # https://github.com/docker/metadata-action
        uses: docker/metadata-action@v3
        with:
          images: ganeshs777/hello-world-3

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ganeshs777/hello-world-3:7.1.${{ github.run_number }}
          labels: "build.url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
